package csapi.common;

public class Table {

	
	/*public static String LSOTABLE = "LSO";
	public static String LSOSTREETTABLE = "LSO_STREET";
	public static String LKUPLSOTYPETABLE = "LKUP_LSO_TYPE";
	
	
	public static String REFLSOTERRITORYTABLE = "REF_LSO_TERRITORY";
	public static String LKUPTERRITORYTABLE = "LKUP_TERRITORY";
	public static String LKUPTERRITORYTYPETABLE = "LKUP_TERRITORY_TYPE";
	
	
	public static String LSOSITEDATATABLE = "LSO_SITEDATA";
	public static String LSOSETBACKTABLE = "LSO_SETBACK";
	public static String LKUPLSOSETBACKTYPETABLE = "LKUP_LSO_SETBACK_TYPE";
	
	
	public static String USERSTABLE = "USERS";
	
	public static String ACTIVITYTABLE = "ACTIVITY";
	public static String REFPROJLSOTABLE = "REF_PROJ_LSO";
	public static String PROJECTTABLE = "PROJECT";
	public static String LKUPACTPROJECTSTATUSTABLE = "LKUP_ACT_PROJECT_STATUS";
	
	
	public static String ACTIVITYTYPETABLE = "ACT_TYPE";
	public static String ACTIVITYSTATUSTABLE = "ACT_STATUS";
	
	
	public static String REFLSOCOMMENTSTABLE = "REF_LSO_COMMENTS ";
	public static String REFPROJECTCOMMENTSTABLE = "REF_PROJECT_COMMENTS";
	public static String REFACTCOMMENTSTABLE = "REF_ACT_COMMENTS";
	public static String NOTESTABLE = "NOTES";
	
	
	public static String REFLSOATTACHMENTSTABLE = "REF_LSO_ATTACHMENTS ";
	public static String REFPROJECTATTACHMENTSTABLE = "REF_PROJECT_ATTACHMENTS";
	public static String REFACTATTACHMENTSTABLE = "REF_ACT_ATTACHMENTS";
	public static String ATTACHMENTSTABLE = "ATTACHMENTS";
	
	
	public static String ACTFIELDVALUETABLE = "ACT_FIELD_VALUE ";
	public static String FIELDTABLE = "FIELD";
	public static String FIELDGROUPSTABLE = "FIELD_GROUPS ";
	
	public static String PROJECTFIELDVALUETABLE = "PROJECT_FIELD_VALUE ";
	public static String LSOFIELDVALUETABLE = "LSO_FIELD_VALUE";*/

	//ALL TABLE LIST
	public static String ACTFEETABLE = "ACT_FEE";
	public static String ACTFIELDVALUETABLE =  "ACT_FIELD_VALUE";
	public static String ACTSTATUSTABLE =  "ACT_STATUS";
	public static String ACTSUBTYPETABLE =  "LKUP_ACT_SUBTYPE";
	public static String ACTTYPETABLE =  "LKUP_ACT_TYPE";
	public static String LKUPACTTYPETABLE =  "LKUP_ACT_TYPE";
	public static String ACTIVITYTABLE =  "ACTIVITY";
	public static String APPOINTMENTTABLE =  "APPOINTMENT";
	public static String APPOINTMENTSCHEDULETABLE =  "APPOINTMENT_SCHEDULE";
	public static String ASSESSORDATATABLE =  "ASSESSOR_DATA";
	public static String ASSESSOROWNERTABLE =  "ASSESSOR_OWNER";
	public static String ASSESSORSITETABLE =  "ASSESSOR_SITE";
	public static String ASSESSORTAXTABLE =  "ASSESSOR_TAX";
	public static String ATTACHMENTSTABLE =  "ATTACHMENTS";
	public static String AVAILABILITYTABLE =  "AVAILABILITY";
	public static String AVAILABILITYCUSTOMTABLE =  "AVAILABILITY_CUSTOM";
	public static String AVAILABILITYDEFAULTTABLE =  "AVAILABILITY_DEFAULT";
	public static String DEPARTMENTTABLE =  "DEPARTMENT";
	public static String DOTACCOUNTFIELDVALUETABLE =  "DOT_ACCOUNT_FIELD_VALUE";
	public static String FEETABLE =  "FEE";
	public static String FEENAMEVALUETABLE =  "FEE_NAME_VALUE";
	public static String FEEASSOCIATEDTABLE =  "FEE_ASSOCIATED";
	public static String FEECALCTABLE =  "FEE_CALC";
	public static String FEECHARTTABLE =  "FEE_CHART";
	public static String FEECHARTGROUPTABLE =  "FEE_CHART_GROUP";
	public static String FEEFIELDVALUETABLE =  "FEE_FIELD_VALUE";
	public static String FEEGROUPTABLE =  "FEE_GROUP";
	public static String FEEWORKSHEETTABLE =  "FEE_WORKSHEET";
	public static String REFFEEFORMULATABLE =  "REF_FEE_FORMULA";
	
	public static String REFFEEINTERRITORYTABLE =  "REF_FEE_IN_TERRITORY";
	public static String REFFEEOUTTERRITORYTABLE =  "REF_FEE_OUT_TERRITORY";
	
	public static String REFFEEINDIVISIONSTABLE =  "REF_FEE_IN_DIVISIONS";
	public static String REFFEEOUTDIVISIONSTABLE =  "REF_FEE_OUT_DIVISIONS";
	
	public static String FIELDTABLE =  "FIELD";
	public static String FIELDCHOICESTABLE =  "FIELD_CHOICES";
	public static String FIELDDEFAULTTABLE =  "FIELD_DEFAULT";
	public static String FIELDGROUPSTABLE =  "FIELD_GROUPS";
	public static String FINANCEMAPTABLE =  "FINANCE_MAP";
	public static String LIBRARYGROUPTABLE =  "LIBRARY_GROUP";
	public static String LIBRARYTABLE =  "LIBRARY";
	public static String LKUPPROJECTSTATUSTABLE =  "LKUP_PROJECT_STATUS";
	public static String LKUPACTSTATUSTABLE =  "LKUP_ACT_STATUS";
	public static String LKUPCIPTABLE =  "LKUP_CIP";
	public static String LKUPHOLIDAYTYPETABLE =  "LKUP_HOLIDAY_TYPE";
	public static String LKUPVOIPMENUTABLE =  "LKUP_VOIP_MENU";
	public static String LKUPVOIPLOGICTABLE =  "LKUP_VOIP_LOGIC";
	public static String LKUPAPPOINTMENTTYPETABLE =  "LKUP_APPOINTMENT_TYPE";
	public static String LKUPATTACHTYPETABLE =  "LKUP_ATTACHMENTS_TYPE";
	public static String LKUPFIELDTYPETABLE =  "LKUP_FIELD_TYPE";
	public static String LKUPFIELDITYPETABLE =  "LKUP_FIELD_ITYPE";
	public static String LKUPFORMULATABLE =  "LKUP_FORMULA";
	public static String LKUPFUNCTIONSTABLE =  "LKUP_FUNCTIONS";
	public static String LKUPHOLDTYPETABLE =  "LKUP_HOLDS_TYPE";
	public static String LKUPHOLDSTATUSTABLE =  "LKUP_HOLDS_STATUS";
	public static String LKUPLIBRARYTABLE =  "LKUP_LIBRARY";
	public static String LKUPLSOSETBACKTYPETABLE =  "LKUP_LSO_SETBACK_TYPE";
	public static String LKUPLSOTYPETABLE =  "LKUP_LSO_TYPE";
	public static String LKUPMODULESTABLE =  "LKUP_MODULES";
	public static String LKUPSOLRURLTABLE =  "LKUP_SOLR_URL";
	public static String LKUPJOBSCHEDULETABLE =  "LKUP_JOB_SCHEDULE_TYPE";
	
	public static String LKUPMODULETABLE =  "LKUP_MODULE";
	public static String ASSESSORIMPORTLOG =  "ASSESSOR_IMPORT_LOG";
	public static String LKUPTEMPLATETYPETABLE =  "LKUP_TEMPLATE_TYPE";

	public static String LKUPNOTESTYPETABLE =  "LKUP_NOTES_TYPE";
	public static String LKUPNOTIFICATIONSCHEDULETYPETABLE =  "LKUP_NOTIFICATION_SCHEDULE_TYPE";
	public static String LKUPNOTIFICATIONTYPETABLE =  "LKUP_NOTIFICATION_TYPE";
	public static String LKUPPEOPLELICENSETYPETABLE =  "LKUP_PEOPLE_LICENSE_TYPE";
	public static String LKUPPERMISSIONTABLE =  "LKUP_PERMISSION";
	public static String LKUPREVIEWSTATUSTABLE =  "LKUP_REVIEW_STATUS";
	public static String LKUPREVIEWTYPETABLE =  "LKUP_REVIEW_TYPE";
	public static String LKUPTERRITORYTABLE =  "LKUP_TERRITORY";
	public static String LKUPTERRITORYTYPETABLE =  "LKUP_TERRITORY_TYPE";
	public static String LKUPDIVISIONSTABLE =  "LKUP_DIVISIONS";
	public static String LKUPDIVISIONSTYPETABLE =  "LKUP_DIVISIONS_TYPE";
	public static String LKUPDIVISIONSGROUPTABLE =  "LKUP_DIVISIONS_GROUP";
	public static String LKUPTRANSACTIONTYPETABLE =  "LKUP_TRANSACTION_TYPE";
	public static String LKUPUSERTYPETABLE =  "LKUP_USERS_TYPE";
	public static String LKUPPATTERNTABLE =  "LKUP_PATTERN";
	public static String LOGNOTIFICATIONTABLE =  "LOG_NOTIFICATION";
	public static String LSOTABLE =  "LSO";
	public static String LSOAPNTABLE =  "LSO_APN";
	public static String LSOFIELDVALUETABLE =  "LSO_FIELD_VALUE";
	public static String LSOGEOTABLE =  "LSO_GEO";
	public static String LSOSETBACKTABLE =  "LSO_SETBACK";
	public static String LSOSITEDATATABLE =  "LSO_SITEDATA";
	public static String LSOSITEDATAFIELDVALUETABLE =  "LSO_SITEDATA_FIELD_VALUE";
	public static String LSOSTREETTABLE =  "LSO_STREET";
	public static String LSOSTREETALIASTABLE =  "LSO_STREET_ALIAS";
	public static String LSOTYPEFIELDGROUPSTABLE =  "LSO_TYPE_FIELD_GROUPS";
	public static String NOTESTABLE =  "NOTES";
	public static String NOTESRECIPIENTSTABLE =  "NOTES_RECIPIENTS";
	public static String NOTIFICATIONTABLE =  "NOTIFICATION";
	public static String NOTIFICATIONSCHEDULETABLE =  "NOTIFICATION_SCHEDULE";
	public static String OBCBHCSACTTYPEMAPTABLE =  "OBC_BHCS_ACT_TYPE_MAP";
	public static String OBCBHCSFEEMAPTABLE =  "OBC_BHCS_FEE_MAP";
	public static String OBCBHCSHOLDIDMAPTABLE =  "OBC_BHCS_HOLD_ID_MAP";
	public static String OBCBHCSLIBRARYMAPTABLE =  "OBC_BHCS_LIBRARY_MAP";
	public static String OBCBHCSLKUPFEEMAPTABLE =  "OBC_BHCS_LKUP_FEE_MAP";
	public static String OBCBHCSLKUPREVIEWSTATUSMAPTABLE =  "OBC_BHCS_LKUP_REVIEW_STATUS_MAP";
	public static String OBCBHCSPAYMENTMAPTABLE =  "OBC_BHCS_PAYMENT_MAP";
	public static String OBCBHCSPROJECTACTIVITYIDMAPTABLE =  "OBC_BHCS_PROJECT_ACTIVITY_ID_MAP";
	public static String OBCBHCSPROJECTTYPEIDMAPTABLE =  "OBC_BHCS_PROJECT_TYPE_ID_MAP";
	public static String OBCBHCSREVIEWGROUPMAPTABLE =  "OBC_BHCS_REVIEW_GROUP_MAP";
	public static String OBCBHCSREVIEWMAPTABLE =  "OBC_BHCS_REVIEW_MAP";
	public static String OBCBHCSSITEDATAMAPTABLE =  "OBC_BHCS_SITEDATA_MAP";
	public static String OBCBHCSTERRITORYMAPTABLE =  "OBC_BHCS_TERRITORY_MAP";
	public static String OBCBHCSDIVISIONSMAPTABLE =  "OBC_BHCS_DIVISIONS_MAP";
	public static String OBCBHCSUSERMAPTABLE =  "OBC_BHCS_USER_MAP";
	public static String PAYMENTTABLE =  "PAYMENT";
	public static String PAYMENTDETAILTABLE =  "PAYMENT_DETAIL";
	public static String PEOPLETABLE =  "PEOPLE";
	public static String PEOPLELICENSETABLE =  "PEOPLE_LICENSE";
	public static String PROJECTTABLE =  "PROJECT";
	public static String PROJECTFIELDVALUETABLE =  "PROJECT_FIELD_VALUE";
	public static String LKUPPROJECTTYPETABLE =  "LKUP_PROJECT_TYPE";
	public static String REFACTACTIVITYTABLE =  "REF_ACT_ACTIVITY";
	public static String REFACTATTACHMENTSTABLE =  "REF_ACT_TYPE_ATTACHMENT_TYPE";
	public static String REFACTCOMMENTSTABLE =  "REF_ACT_COMMENTS";
	public static String REFACTFIELDGROUPSTABLE =  "REF_ACT_FIELD_GROUPS";
	
	public static String REFACTMODULETABLE =  "REF_ACT_MODULE";
	public static String REFPROJECTMODULETABLE =  "REF_PROJECT_MODULE";
	public static String REFLSOMODULETABLE =  "REF_LSO_MODULE";

	public static String REFVOIPTRANSFERTABLE =  "REF_VOIP_TRANSFER";
	
	public static String REFACTLIBRARYGROUPTABLE =  "REF_ACT_LIBRARY_GROUP";
	public static String REFPROJECTLIBRARYGROUPTABLE =  "REF_PROJECT_LIBRARY_GROUP";
	public static String REFLSOLIBRARYGROUPTABLE =  "REF_LSO_LIBRARY_GROUP";
	public static String REFLIBRARYGROUPTABLE =  "REF_LIBRARY_GROUP";
	
	public static String REFLSOTYPEFIELDGROUPSTABLE =  "REF_LSO_FIELD_GROUPS";
	public static String REFACTHOLDTABLE =  "REF_ACT_HOLD";
	
	public static String REFACTTYPEHOLDSTABLE =  "REF_ACT_TYPE_HOLDS";
	
	public static String REFACTLIBRARYTABLE =  "REF_ACT_LIBRARY";
	public static String REFACTLKUPLIBRARYTABLE =  "REF_ACT_LKUP_LIBRARY";
	public static String REFACTLSOTABLE =  "REF_ACT_LSO";
	public static String REFACTPROJECTTYPETABLE =  "REF_ACT_PROJECT_TYPE";
	public static String REFACTREVIEWTABLE =  "REF_ACT_REVIEW";
	public static String REFACTREVIEWGROUPTABLE =  "REF_ACT_REVIEW_GROUP";
	public static String REFPROJECTREVIEWGROUPTABLE =  "REF_PROJECT_REVIEW_GROUP";
	public static String REFLSOREVIEWGROUPTABLE =  "REF_LSO_REVIEW_GROUP";
	
	public static String REFACTSUBTYPETABLE =  "REF_ACT_SUBTYPE";
	public static String REFACTTYPEFEETABLE =  "REF_ACT_TYPE_FEE";
	public static String REFACTWORKFLOWTABLE =  "REF_ACT_WORKFLOW";
	public static String REFACTWORKSHEETTABLE =  "REF_ACT_WORKSHEET";
	public static String REFACTIVITYUSERSTABLE =  "REF_ACTIVITY_USERS";
	public static String REFAPPOINTMENTATTENDEESTABLE =  "REF_APPOINTMENT_ATTENDEES";
	public static String REFAPPOINTMENTNOTESTABLE =  "REF_APPOINTMENT_NOTES";
	public static String REFAPPOINTMENTNOTIFICATIONTABLE =  "REF_APPOINTMENT_NOTIFICATION";
	public static String REFCHOICEFIELDGROUPSTABLE =  "REF_CHOICE_FIELD_GROUPS";
	public static String REFCOMBOREVIEWACTIONTABLE =  "REF_COMBOREVIEW_ACTION";
	public static String REFFEEGROUPTABLE =  "REF_FEE_GROUP";
	public static String REFLIBRARYTABLE =  "REF_LIBRARY";
	public static String REFLSOATTACHMENTSTABLE =  "REF_LSO_TYPE_ATTACHMENT_TYPE";
	public static String REFLSOCOMMENTSTABLE =  "REF_LSO_COMMENTS";
	public static String REFLSOFIELDVALUETABLE =  "REF_LSO_FIELD_VALUE";
	public static String REFLSOHOLDTABLE =  "REF_LSO_HOLD";
	
	//public static String REFACTTYPEHOLDSTABLE =  "REF_ACT_TYPE_HOLDS";
	public static String REFLSOLKUPLIBRARYTABLE =  "REF_LSO_LKUP_LIBRARY";
	public static String REFLSOSITEDATAFIELDGROUPSTABLE =  "REF_LSO_SITEDATA_FIELD_GROUPS";
	public static String REFLSOTERRITORYTABLE =  "REF_LSO_TERRITORY";
	public static String REFLSODIVISIONSTABLE =  "REF_LSO_DIVISIONS";
	public static String REFMODULEFUNCTIONSTABLE =  "REF_MODULE_FUNCTIONS";
	public static String REFNOTIFICATIONRECIPIENTSTABLE =  "REF_NOTIFICATION_RECIPIENTS";
	public static String REFPEOPLEATTACHMENTSTABLE =  "REF_PEOPLE_TYPE_ATTACHMENT_TYPE";
	public static String REFPLANCHECKNOTESTABLE =  "REF_PLAN_CHECK_NOTES";
	public static String REFLSOPROJECTTABLE =  "REF_LSO_PROJECT";
	public static String REFPROJECTTABLE =  "REF_PROJECT";
	public static String REFPROJECTATTACHMENTSTABLE =  "REF_PROJECT_TYPE_ATTACHMENT_TYPE";
	public static String REFPROJECTFIELDGROUPSTABLE =  "REF_PROJECT_FIELD_GROUPS";
	public static String REFPROJECTCOMMENTSTABLE =  "REF_PROJECT_COMMENTS";
	public static String REFPROJECTHOLDTABLE =  "REF_PROJECT_HOLD";
	public static String REFPROJECTLIBRARYTABLE =  "REF_PROJECT_LIBRARY";
	public static String REFPROJECTLKUPLIBRARYTABLE =  "REF_PROJECT_LKUP_LIBRARY";
	public static String REFPROJECTUSERSTABLE =  "REF_PROJECT_USERS";
	public static String REFREVIEWAPPOINTMENTTABLE =  "REF_REVIEW_APPOINTMENT";
	public static String REFREVIEWATTACHMENTSTABLE =  "REF_REVIEW_ATTACHMENTS";
	public static String REFREVIEWFIELDGROUPSTABLE =  "REF_REVIEW_FIELD_GROUPS";
	public static String REFREVIEWLIBRARYTABLE =  "REF_REVIEW_LIBRARY";
	public static String REFREVIEWNOTESTABLE =  "REF_REVIEW_NOTES";
	public static String REFREVIEWTEAMTABLE =  "REF_REVIEW_TEAM";
	public static String REFREVIEWWORKFLOWTABLE =  "REF_REVIEW_WORKFLOW";
	public static String REFTERRITORYPROJECTTYPETABLE =  "REF_TERRITORY_PROJECT_TYPE";
	public static String REFDIVISIONSPROJECTTYPETABLE =  "REF_DIVISIONS_PROJECT_TYPE";
	public static String REFUSERATTACHMENTSTABLE =  "REF_USERS_ATTACHMENTS";
	public static String REFUSERAVAILABILITYTABLE =  "REF_USERS_AVAILABILITY";
	public static String REFUSERFUNCTIONSTABLE =  "REF_USERS_FUNCTIONS";
	public static String REFUSERSGROUPTABLE =  "REF_USERS_GROUP";
	public static String REFUSERSYSTEMSTABLE =  "REF_USERS_SYSTEMS";
	public static String REFUSERGROUPAVAILABILITYTABLE =  "REF_USERGROUP_AVAILABILITY";
	public static String REFVOIPREVIEW =  "REF_VOIP_REVIEW";
	public static String REFUSERSTABLE =  "REF_USERS";
	public static String REVIEWTABLE =  "REVIEW";
	public static String REVIEWACTIONTABLE =  "REVIEW_ACTION";
	public static String REVIEWFIELDVALUETABLE =  "REVIEW_FIELD_VALUE";
	public static String REVIEWGROUPTABLE =  "REVIEW_GROUP";
	public static String REVIEWTYPETABLE =  "REVIEW_TYPE";
	public static String STAFFTABLE =  "STAFF";
	public static String USERFIELDVALUETABLE =  "USERS_FIELD_VALUE";
	public static String USERSGROUPTABLE =  "USERS_GROUP";
	public static String REFTEAMTABLE =  "REF_TEAM";
	public static String LKUPTEAMTYPETABLE =  "LKUP_TEAM_TYPE";
	
	public static String REFUSERROLESTABLE =  "REF_USERS_ROLES";
	public static String LKUPROLESTABLE =  "LKUP_ROLES";
	
	public static String USERSTABLE =  "USERS";
	public static String WORKFLOWTABLE =  "WORKFLOW";
	public static String WORKFLOWGROUPTABLE =  "WORKFLOW_GROUP";
	public static String WORKFLOWTYPETABLE =  "WORKFLOW_TYPE";
	public static String WORKFLOWVALUES = "WORKFLOW_VALUES"; 

	public static String TEMPLATETABLE = "TEMPLATE"; 
	public static String LKUPRESOLUTIONSTATUSTABLE =  "LKUP_RESOLUTION_STATUS";
	
	public static String LKUPPAYMENTMETHODTABLE =  "LKUP_PAYMENT_METHOD";
	public static String LKUPPAYMENTTRANSACTIONTYPETABLE =  "LKUP_PAYMENT_TRANSACTION_TYPE";
	public static String CONTENTTABLE = "CONTENT"; 
	public static String REFLSOAPNTABLE =  "REF_LSO_APN";
}
